### ISSUE TITLE
Couldn't deploy when including a specific note

### ISSUE THREAD

**Issue by UriMtzF** [oleeskild/obsidian-digital-garden#143]
Hi! I was trying the plugin and all my deploys failed. Reading more about the error, a specific note [(this one)](https://github.com/UriMtzF/mathsidian/blob/main/src/site/notes/Aritm%C3%A9tica/Potenciaci%C3%B3n.md) was causing the error.

When I didn't include the note, everythin went good so I don't see a clear reason why it's failing.

Here's the log, thanks in advance

```
8:24:57 PM: build-image version: d55944c047ef0aee2ac01971edde72cb2a50acfe (focal)
8:24:57 PM: build-image tag: v4.16.1
8:24:57 PM: buildbot version: a1ec8307ac4591dcd155485cdfce7d7be735ab26
8:24:58 PM: Fetching cached dependencies
8:24:58 PM: Starting to download cache of 110.8MB
8:24:59 PM: Finished downloading cache in 998.152947ms
8:24:59 PM: Starting to extract cache
8:24:59 PM: Finished extracting cache in 824.903039ms
8:24:59 PM: Finished fetching cache in 1.902971641s
8:24:59 PM: Starting to prepare the repo for build
8:25:00 PM: Preparing Git Reference refs/heads/main
8:25:01 PM: Parsing package.json dependencies
8:25:02 PM: Starting build script
8:25:02 PM: Installing dependencies
8:25:02 PM: Python version set to 2.7
8:25:02 PM: Started restoring cached node version
8:25:03 PM: Finished restoring cached node version
8:25:03 PM: v16.19.0 is already installed.
8:25:03 PM: Now using node v16.19.0 (npm v8.19.3)
8:25:03 PM: Enabling node corepack
8:25:03 PM: Started restoring cached build plugins
8:25:03 PM: Finished restoring cached build plugins
8:25:04 PM: Attempting ruby version 2.7.2, read from environment
8:25:04 PM: Using ruby version 2.7.2
8:25:04 PM: Using PHP version 8.0
8:25:04 PM: No npm workspaces detected
8:25:04 PM: Started restoring cached node modules
8:25:04 PM: Finished restoring cached node modules
8:25:05 PM: Started restoring cached go cache
8:25:05 PM: Finished restoring cached go cache
8:25:06 PM: go version go1.19.4 linux/amd64
8:25:06 PM: Detected 1 framework(s)
8:25:06 PM: "eleventy" at version "1.0.2"
8:25:06 PM: Installing missing commands
8:25:06 PM: Verify run directory
8:25:06 PM: Section completed: initializing
8:25:07 PM: ​
8:25:07 PM:   Netlify Build                                                 
8:25:07 PM: ────────────────────────────────────────────────────────────────
8:25:07 PM: ​
8:25:07 PM: ❯ Version
8:25:07 PM:   @netlify/build 29.4.0
8:25:07 PM: ​
8:25:07 PM: ❯ Flags
8:25:07 PM:   baseRelDir: true
8:25:07 PM:   buildId: 63b7866397c92000086d7b8e
8:25:07 PM:   deployId: 63b7866397c92000086d7b90
8:25:07 PM: ​
8:25:07 PM: ❯ Current directory
8:25:07 PM:   /opt/build/repo
8:25:07 PM: ​
8:25:07 PM: ❯ Config file
8:25:07 PM:   /opt/build/repo/netlify.toml
8:25:07 PM: ​
8:25:07 PM: ❯ Context
8:25:07 PM:   production
8:25:07 PM: ​
8:25:07 PM:   1. build.command from netlify.toml                            
8:25:07 PM: ────────────────────────────────────────────────────────────────
8:25:07 PM: ​
8:25:07 PM: $ npm install && npm run build
8:25:10 PM: up to date, audited 605 packages in 2s
8:25:10 PM: 72 packages are looking for funding
8:25:10 PM:   run `npm fund` for details
8:25:10 PM: 12 vulnerabilities (6 moderate, 5 high, 1 critical)
8:25:10 PM: To address issues that do not require attention, run:
8:25:10 PM:   npm audit fix
8:25:10 PM: Some issues need review, and may require choosing
8:25:10 PM: a different dependency.
8:25:10 PM: Run `npm audit` for details.
8:25:10 PM: > web@1.0.0 build
8:25:10 PM: > npm-run-all build:*
8:25:10 PM: > web@1.0.0 build:eleventy
8:25:10 PM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
8:25:12 PM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
8:25:12 PM: [11ty] 1. Having trouble rendering njk template ./src/site/notes/Aritmética/Potenciación.md (via TemplateContentRenderError)
8:25:12 PM: [11ty] 2. (./src/site/notes/Aritmética/Potenciación.md) [Line 7, Column 260]
8:25:12 PM: [11ty]   expected variable end (via Template render error)
8:25:12 PM: [11ty]
8:25:12 PM: [11ty] Original error stack trace: Template render error: (./src/site/notes/Aritmética/Potenciación.md) [Line 7, Column 260]
8:25:12 PM: [11ty]   expected variable end
8:25:12 PM: [11ty]     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:36:11)
8:25:12 PM: [11ty]     at Template.init (/opt/build/repo/node_modules/nunjucks/src/environment.js:511:19)
8:25:12 PM: [11ty]     at Template.Obj (/opt/build/repo/node_modules/nunjucks/src/object.js:62:15)
8:25:12 PM: [11ty]     at new Template (/opt/build/repo/node_modules/nunjucks/src/environment.js:478:18)
8:25:12 PM: [11ty]     at Nunjucks.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:480:14)
8:25:12 PM: [11ty]     at Markdown.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:28)
8:25:12 PM: [11ty]     at TemplateRender.getCompiledTemplate (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:232:26)
8:25:12 PM: [11ty]     at Template.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:296:42)
8:25:12 PM: [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
8:25:12 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
8:25:12 PM: [11ty]     at async Template._render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:390:16)
8:25:12 PM: [11ty] Benchmark    359ms  26%     1× (Data) `./src/site/_data/meta.js`
8:25:12 PM: [11ty] Copied 1 file / Wrote 0 files in 1.16 seconds (v1.0.2)
8:25:12 PM: ERROR: "build:eleventy" exited with 1.
8:25:12 PM: ​
8:25:12 PM:   "build.command" failed                                        
8:25:12 PM: ────────────────────────────────────────────────────────────────
8:25:12 PM: ​
8:25:12 PM:   Error message
8:25:12 PM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
8:25:12 PM: ​
8:25:12 PM:   Error location
8:25:12 PM:   In build.command from netlify.toml:
8:25:12 PM:   npm install && npm run build
8:25:12 PM: ​
8:25:12 PM:   Resolved config
8:25:12 PM:   build:
8:25:12 PM:     command: npm install && npm run build
8:25:12 PM:     commandOrigin: config
8:25:12 PM:     publish: /opt/build/repo/dist
8:25:12 PM:     publishOrigin: config
8:25:12 PM:   functionsDirectory: /opt/build/repo/netlify/functions
8:25:12 PM:   redirects:
8:25:12 PM:     - from: /api/*      status: 200      to: /.netlify/functions/:splat    - from: /*      status: 404      to: /404  redirectsOrigin: configCaching artifacts
8:25:12 PM: Started saving node modules
8:25:12 PM: Finished saving node modules
8:25:12 PM: Started saving build plugins
8:25:12 PM: Finished saving build plugins
8:25:12 PM: Started saving pip cache
8:25:12 PM: Finished saving pip cache
8:25:12 PM: Started saving emacs cask dependencies
8:25:12 PM: Finished saving emacs cask dependencies
8:25:12 PM: Started saving maven dependencies
8:25:12 PM: Finished saving maven dependencies
8:25:12 PM: Started saving boot dependencies
8:25:12 PM: Finished saving boot dependencies
8:25:12 PM: Started saving rust rustup cache
8:25:12 PM: Finished saving rust rustup cache
8:25:12 PM: Started saving go dependencies
8:25:12 PM: Finished saving go dependencies
8:25:12 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
8:25:12 PM: Failing build: Failed to build site
8:25:12 PM: Finished processing build request in 15.053125076s
```

**Comment by Gonglja** [comment]
Hi, I also have the same problem, the log is as follows:
```
2:49:25 PM: build-image version: d55944c047ef0aee2ac01971edde72cb2a50acfe (focal)
2:49:25 PM: build-image tag: v4.16.1
2:49:25 PM: buildbot version: a1ec8307ac4591dcd155485cdfce7d7be735ab26
2:49:26 PM: Fetching cached dependencies
2:49:26 PM: Starting to download cache of 142.0MB
2:49:26 PM: Finished downloading cache in 821.918457ms
2:49:26 PM: Starting to extract cache
2:49:27 PM: Finished extracting cache in 980.350356ms
2:49:27 PM: Finished fetching cache in 1.858219542s
2:49:27 PM: Starting to prepare the repo for build
2:49:28 PM: Preparing Git Reference refs/heads/main
2:49:28 PM: git clone --filter=blob:none git@github.com:Gonglja/digitalgarden
2:49:29 PM: Parsing package.json dependencies
2:49:30 PM: Starting build script
2:49:30 PM: Installing dependencies
2:49:30 PM: Python version set to 2.7
2:49:31 PM: Started restoring cached node version
2:49:31 PM: Finished restoring cached node version
2:49:31 PM: v16.19.0 is already installed.
2:49:32 PM: Now using node v16.19.0 (npm v8.19.3)
2:49:32 PM: Enabling node corepack
2:49:32 PM: Started restoring cached build plugins
2:49:32 PM: Finished restoring cached build plugins
2:49:32 PM: Attempting ruby version 2.7.2, read from environment
2:49:32 PM: Using ruby version 2.7.2
2:49:33 PM: Using PHP version 8.0
2:49:33 PM: No npm workspaces detected
2:49:33 PM: Started restoring cached node modules
2:49:33 PM: Finished restoring cached node modules
2:49:33 PM: Started restoring cached go cache
2:49:33 PM: Finished restoring cached go cache
2:49:34 PM: go version go1.19.4 linux/amd64
2:49:34 PM: Detected 1 framework(s)
2:49:34 PM: "eleventy" at version "1.0.2"
2:49:34 PM: Installing missing commands
2:49:34 PM: Verify run directory
2:49:34 PM: Section completed: initializing
2:49:36 PM: ​
2:49:36 PM:   Netlify Build                                                 
2:49:36 PM: ────────────────────────────────────────────────────────────────
2:49:36 PM: ​
2:49:36 PM: ❯ Version
2:49:36 PM:   @netlify/build 29.4.0
2:49:36 PM: ​
2:49:36 PM: ❯ Flags
2:49:36 PM:   baseRelDir: true
2:49:36 PM:   buildId: 63b7c474c97f3a0008e0e08a
2:49:36 PM:   deployId: 63b7c474c97f3a0008e0e08c
2:49:36 PM: ​
2:49:36 PM: ❯ Current directory
2:49:36 PM:   /opt/build/repo
2:49:36 PM: ​
2:49:36 PM: ❯ Config file
2:49:36 PM:   /opt/build/repo/netlify.toml
2:49:36 PM: ​
2:49:36 PM: ❯ Context
2:49:36 PM:   production
2:49:36 PM: ​
2:49:36 PM:   1. build.command from netlify.toml                            
2:49:36 PM: ────────────────────────────────────────────────────────────────
2:49:36 PM: ​
2:49:36 PM: $ npm install && npm run build
2:49:38 PM: up to date, audited 605 packages in 2s
2:49:38 PM: 72 packages are looking for funding
2:49:38 PM:   run `npm fund` for details
2:49:38 PM: 12 vulnerabilities (6 moderate, 5 high, 1 critical)
2:49:38 PM: To address issues that do not require attention, run:
2:49:38 PM:   npm audit fix
2:49:38 PM: Some issues need review, and may require choosing
2:49:38 PM: a different dependency.
2:49:38 PM: Run `npm audit` for details.
2:49:38 PM: > web@1.0.0 build
2:49:38 PM: > npm-run-all build:*
2:49:38 PM: > web@1.0.0 build:eleventy
2:49:38 PM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
2:49:39 PM: [11ty] Problem writing Eleventy templates: (more in DEBUG output)
2:49:39 PM: [11ty] 1. Having trouble rendering njk template ./src/site/notes/D-软件技能/obsidian/obsidian 插件 DigitalGarden 的测试.md (via TemplateContentRenderError)
2:49:39 PM: [11ty] 2. (./src/site/notes/D-软件技能/obsidian/obsidian 插件 DigitalGarden 的测试.md) [Line 1884, Column 23]
2:49:39 PM: [11ty]   expected variable end (via Template render error)
2:49:39 PM: [11ty]
2:49:39 PM: [11ty] Original error stack trace: Template render error: (./src/site/notes/D-软件技能/obsidian/obsidian 插件 DigitalGarden 的测试.md) [Line 1884, Column 23]
2:49:39 PM: [11ty]   expected variable end
2:49:39 PM: [11ty]     at Object._prettifyError (/opt/build/repo/node_modules/nunjucks/src/lib.js:36:11)
2:49:39 PM: [11ty]     at Template.init (/opt/build/repo/node_modules/nunjucks/src/environment.js:511:19)
2:49:39 PM: [11ty]     at Template.Obj (/opt/build/repo/node_modules/nunjucks/src/object.js:62:15)
2:49:39 PM: [11ty]     at new Template (/opt/build/repo/node_modules/nunjucks/src/environment.js:478:18)
2:49:39 PM: [11ty]     at Nunjucks.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:480:14)
2:49:39 PM: [11ty]     at Markdown.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/Engines/Markdown.js:63:28)
2:49:39 PM: [11ty]     at TemplateRender.getCompiledTemplate (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateRender.js:232:26)
2:49:39 PM: [11ty]     at Template.compile (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:296:42)
2:49:39 PM: [11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2:49:39 PM: [11ty]     at async Template._render (/opt/build/repo/node_modules/@11ty/eleventy/src/TemplateContent.js:390:16)
2:49:40 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
2:49:39 PM: [11ty] Benchmark    115ms  24%     1× (Data) `./src/site/_data/meta.js`
2:49:39 PM: [11ty] Copied 1 file / Wrote 0 files in 0.25 seconds (v1.0.2)
2:49:39 PM: ERROR: "build:eleventy" exited with 1.
2:49:39 PM: ​
2:49:39 PM:   "build.command" failed                                        
2:49:39 PM: ────────────────────────────────────────────────────────────────
2:49:39 PM: ​
2:49:39 PM:   Error message
2:49:39 PM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
2:49:39 PM: ​
2:49:39 PM:   Error location
2:49:39 PM:   In build.command from netlify.toml:
2:49:39 PM:   npm install && npm run build
2:49:39 PM: ​
2:49:39 PM:   Resolved config
2:49:39 PM:   build:
2:49:39 PM:     command: npm install && npm run build
2:49:39 PM:     commandOrigin: config
2:49:39 PM:     publish: /opt/build/repo/dist
2:49:39 PM:     publishOrigin: config
2:49:39 PM:   functionsDirectory: /opt/build/repo/netlify/functions
2:49:39 PM:   redirects:
2:49:40 PM:     - from: /api/*
      status: 200
      to: /.netlify/functions/:splat
    - from: /*
      status: 404
      to: /404
  redirectsOrigin: config
Caching artifacts
2:49:40 PM: Started saving node modules
2:49:40 PM: Finished saving node modules
2:49:40 PM: Started saving build plugins
2:49:40 PM: Finished saving build plugins
2:49:40 PM: Started saving pip cache
2:49:40 PM: Finished saving pip cache
2:49:40 PM: Started saving emacs cask dependencies
2:49:40 PM: Finished saving emacs cask dependencies
2:49:40 PM: Started saving maven dependencies
2:49:40 PM: Finished saving maven dependencies
2:49:40 PM: Started saving boot dependencies
2:49:40 PM: Finished saving boot dependencies
2:49:40 PM: Started saving rust rustup cache
2:49:40 PM: Finished saving rust rustup cache
2:49:40 PM: Started saving go dependencies
2:49:40 PM: Finished saving go dependencies
2:49:40 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:49:40 PM: Failing build: Failed to build site
2:49:40 PM: Finished processing build request in 14.467408046s
```
In the place where the error was indicated, I found that I was using the following syntax

````
```mermaid
graph TB
	s=start  e=end  f=fork  n=normal

	s([开始])-->f1{{if条件}};

	f1--true-->n1[if语句块]-->e([结束]);
	f1--false-->f2{{else if条件}};

	f2--true-->n2[else if语句块]-->e;
	f2--false-->n3[else语句块]-->e;
```
````

**Comment by wheresalice** [comment]
I raised the same issue as #271 not realizing that this ticket already exists

The `{{if条件}}` gets treated as jinja template which eleventy attempts to execute. It fails to do so because it isn't fully valid jinja code
