### ISSUE TITLE
 Error 

### ISSUE THREAD

**Issue by LeiYanhua** [oleeskild/obsidian-digital-garden#214]
[09:41:29.543] Running build in Cleveland, USA (East) – cle1
[09:41:29.601] Cloning github.com/LeiYanhua/china-law (Branch: main, Commit: abd6805)
[09:41:29.849] Previous build cache not available
[09:41:30.169] Cloning completed: 567.757ms
[09:41:30.287] Running "vercel build"
[09:41:30.742] Vercel CLI 28.16.10

>[09:41:31.713] Running "install" command: `npm install`...
[09:41:35.671] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[09:41:36.074] npm WARN deprecated mkdirp@0.5.6: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[09:41:36.093] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[09:41:36.780] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[09:41:40.040] 

[09:41:40.041] added 515 packages, and audited 516 packages in 8s
[09:41:40.041] 
[09:41:40.041] 87 packages are looking for funding
[09:41:40.041]   run `npm fund` for details
[09:41:40.048] 
[09:41:40.049] 7 vulnerabilities (6 high, 1 critical)
[09:41:40.049] 
[09:41:40.049] To address issues that do not require attention, run:
[09:41:40.049]   npm audit fix
[09:41:40.049] 
[09:41:40.049] Some issues need review, and may require choosing
[09:41:40.049] a different dependency.
[09:41:40.049] 
[09:41:40.400] 
[09:41:40.400] > web@1.0.0 build
[09:41:40.401] > npm-run-all get-theme build:*
[09:41:40.401] 
[09:41:40.855] 
[09:41:40.857] > web@1.0.0 get-theme
[09:41:40.857] > node src/site/get-theme.js
[09:41:40.857] 
[09:41:41.287] 
[09:41:41.287] > web@1.0.0 build:eleventy
[09:41:41.288] > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
[09:41:41.288] 

>[09:41:42.072] [11ty] Unhandled rejection in promise: (more in DEBUG output)
[09:41:42.072] [11ty] glob.sync is not a function (via TypeError)
[09:41:42.072] [11ty] 
[09:41:42.072] [11ty] Original error stack trace: TypeError: glob.sync is not a function
[09:41:42.072] [11ty]     at module.exports (/vercel/path0/src/site/_data/meta.js:12:25)
[09:41:42.072] [11ty]     at TemplateData.getDataValue (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:524:29)
[09:41:42.073] [11ty]     at async TemplateData.getAllGlobalData (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:307:18)
[09:41:42.073] [11ty]     at async /vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:361:26
[09:41:42.091] ERROR: "build:eleventy" exited with 1.
[09:41:42.113] Error: Command "npm run build" exited with 1
[09:41:42.249]

**Comment by oleeskild** [comment]
Seems you are missing a package, that should be present in your package.json. Try  [updating the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) and see if that helps.
