### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by no251-1** [oleeskild/obsidian-digital-garden#224]
<html>
<body>

Expand 41 Lines
--
11:45:45.820 | [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'docId')
11:45:45.821 | [11ty]     at Object.render_footnote_anchor_name [as footnote_anchor_name] (/vercel/path0/node_modules/markdown-it-footnote/index.js:12:18)
11:45:45.821 | [11ty]     at Object.render_footnote_ref [as footnote_ref] (/vercel/path0/node_modules/markdown-it-footnote/index.js:30:27)
11:45:45.821 | [11ty]     at Renderer.render (/vercel/path0/node_modules/markdown-it/lib/renderer.js:332:38)
11:45:45.821 | [11ty]     at /vercel/path0/src/helpers/utils.js:17:36
11:45:45.821 | [11ty]     at Array.forEach (<anonymous>)
11:45:45.821 | [11ty]     at namedHeadings (/vercel/path0/src/helpers/utils.js:15:18)
11:45:45.821 | [11ty]     at Core.process (/vercel/path0/node_modules/markdown-it/lib/parser_core.js:54:13)
11:45:45.821 | [11ty]     at MarkdownIt.parse (/vercel/path0/node_modules/markdown-it/lib/index.js:524:13)
11:45:45.821 | [11ty]     at MarkdownIt.render (/vercel/path0/node_modules/markdown-it/lib/index.js:544:36)
11:45:45.821 | [11ty]     at /vercel/path0/node_modules/@11ty/eleventy/src/Engines/Markdown.js:74:38
11:45:45.822 | [11ty] Benchmark    177ms   9%     1× (Data) `./src/site/_data/filetree.js`
11:45:45.822 | [11ty] Copied 2 files / Wrote 0 files in 1.56 seconds (v1.0.2)
11:45:45.869 | ERROR: "build:eleventy" exited with 1.
11:45:45.890 | Error: Command "npm run build" exited with 1
11:45:46.496 | BUILD_FAILED: Command "npm run build" exited with 1

</body>
</html>
<html>
<body>

[11ty] 1. Having trouble rendering njk template ./src/site/notes/Microelectronics Failure Analysis Desk Reference(7th Edition)/Section 1 Failure Analysis Process and Management/2. Package Failure Analysis-Flow and Technique.md (via TemplateContentRenderError)
--
11:45:45.820 | [11ty] 2. Cannot read properties of undefined (reading 'docId') (via TypeError)

</body>
</html>

i met sucn error when pulish a new note. 
i check my note and find maybe it is caused by using reference citation in title.
this citation is a markdown grammar like this: [^1]
after remove the ciation, my webpage works well.
so i report the error and how to resolve it here, hope it can help someone met the same problem.

**Comment by zahidsyed** [comment]
I can confirm this issue reproduced the same way in my vault. Removing the footnote from the heading fixes the problem.

**Comment by offbrands-studio** [comment]
As marked by @oleeskild - This issue is still present. 
I also found that adding a footnote at the end of a hyperlink can present this error. 

Basically, in Obsidian, if the 'Reader View' can't show the note with the proper footnotes, then it won't be able to be published on the web. That's how I found the hyperlink error that produces this same error.
