### ISSUE TITLE
[ERROR] First deploy by Vercel failed when building

### ISSUE THREAD

**Issue by HorsenLiu** [oleeskild/obsidian-digital-garden#235]
Deployment failed with error.

![image](https://user-images.githubusercontent.com/50764745/225832951-3a8a2b44-484a-4784-b0b6-3561a66aa7e3.png)
![image](https://user-images.githubusercontent.com/50764745/225833215-8ad40dd1-6668-4c41-9f41-896994e3d173.png)

Here is the message:
```bash
[14:46:54.230] Running build in San Francisco, USA (West) – sfo1
[14:46:54.289] Cloning github.com/HorsenLiu/digital-garden (Branch: main, Commit: 06f61bc)
[14:46:54.416] Previous build cache not available
[14:46:55.169] Cloning completed: 883.466ms
[14:46:55.298] Running "vercel build"
[14:46:55.746] Vercel CLI 28.17.0
[14:46:56.698] Running "install" command: `npm install`...
[14:47:00.510] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[14:47:00.553] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[14:47:00.704] npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[14:47:01.633] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[14:47:04.994] 
[14:47:04.994] added 528 packages, and audited 529 packages in 8s
[14:47:04.994] 
[14:47:04.994] 88 packages are looking for funding
[14:47:04.994]   run `npm fund` for details
[14:47:05.006] 
[14:47:05.006] 9 vulnerabilities (1 moderate, 5 high, 3 critical)
[14:47:05.007] 
[14:47:05.007] To address issues that do not require attention, run:
[14:47:05.007]   npm audit fix
[14:47:05.007] 
[14:47:05.007] Some issues need review, and may require choosing
[14:47:05.007] a different dependency.
[14:47:05.007] 
[14:47:05.007] Run `npm audit` for details.
[14:47:05.345] 
[14:47:05.345] > web@1.0.0 build
[14:47:05.345] > npm-run-all get-theme build:*
[14:47:05.345] 
[14:47:05.787] 
[14:47:05.788] > web@1.0.0 get-theme
[14:47:05.788] > node src/site/get-theme.js
[14:47:05.788] 
[14:47:06.207] 
[14:47:06.207] > web@1.0.0 build:eleventy
[14:47:06.208] > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
[14:47:06.208] 
[14:47:07.066] [11ty] Unhandled rejection in promise: (more in DEBUG output)
[14:47:07.066] [11ty] glob.sync is not a function (via TypeError)
[14:47:07.066] [11ty] 
[14:47:07.066] [11ty] Original error stack trace: TypeError: glob.sync is not a function
[14:47:07.066] [11ty]     at module.exports (/vercel/path0/src/site/_data/meta.js:12:25)
[14:47:07.066] [11ty]     at TemplateData.getDataValue (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:524:29)
[14:47:07.066] [11ty]     at async TemplateData.getAllGlobalData (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:307:18)
[14:47:07.066] [11ty]     at async /vercel/path0/node_modules/@11ty/eleventy/src/TemplateData.js:361:26
[14:47:07.085] ERROR: "build:eleventy" exited with 1.
[14:47:07.107] Error: Command "npm run build" exited with 1
[14:47:07.388] BUILD_FAILED: Command "npm run build" exited with 1
```
Maybe I done something wrong. If you haven't seen this error, I will check for my operation.
Thanks a lot.
Horsen.

**Comment by oleeskild** [comment]
Hi!
I did some routine updates on the npm packages yesterday, but forgot to test one of them. Seems the `glob` package have changed their APIs, which crashes the build. I've fixed it now. Try deleting it in Vercel and deploying it again. Then it should work. Let me know how it goes.

**Comment by HorsenLiu** [comment]
It works! Thanks for the quick response!
This plugin helps me a lot, thanks again.

**Comment by zcysxy** [comment]
> Hi! I did some routine updates on the npm packages yesterday, but forgot to test one of them. Seems the `glob` package have changed their APIs, which crashes the build. I've fixed it now. Try deleting it in Vercel and deploying it again. Then it should work. Let me know how it goes.

Hi @oleeskild, seems like I also encountered this issue on Netlify. Should I delete the site and redeploy?
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/48207708/226056692-81932017-649f-4013-b3e2-e0a6d3a0bf92.png">

**Comment by oleeskild** [comment]
You can also just update the template, and you should be good to go

https://dg-docs.ole.dev/getting-started/06-updating-the-template/

**Comment by zcysxy** [comment]
> You can also just update the template, and you should be good to go
> 
> https://dg-docs.ole.dev/getting-started/06-updating-the-template/

Succeeded! Thank you!
