### ISSUE TITLE
Publish doesn't work (anymore?) - Cannot destructure property 'vault'

### ISSUE THREAD

**Issue by bwydoogh** [oleeskild/obsidian-digital-garden#236]
Using version `2.41.0`.

I am having issues (since the latest update) publishing notes. It doesn't work anymore.

When using the command "publish single note" (for a note previously published) I get the following error:

```
TypeError: Cannot destructure property 'vault' of 'this.app' as it is undefined.
    at Object.eval (plugin:digitalgarden:12143:17)
    at Generator.next (<anonymous>)
    at eval (plugin:digitalgarden:78:61)
    at new Promise (<anonymous>)
    at __async (plugin:digitalgarden:62:10)
    at Object.publishSingleNote [as callback] (plugin:digitalgarden:12141:12)
    at uR (app.js:1:1526336)
    at t.onChooseItem (app.js:1:1865376)
    at t.eval (plugin:hotkey-helper:1:8424)
    at t.i [as onChooseItem] (plugin:hotkey-helper:1:834)
```

Any idea what is going on?

**Comment by oleeskild** [comment]
Sorry, my bad. Rewrote some of the command logic in the last release, and didn't test it properly. Thanks for letting me know! I've released version 2.41.1 which should fix this!
