### ISSUE TITLE
Deployment failed both at Vercel and Netlify

### ISSUE THREAD

**Issue by bliang17** [oleeskild/obsidian-digital-garden#288]
All was fine until recently I am unable to deploy anything either on Netlify or Vercel.

I have tried deleting and re-install Digital Garden in Obsidian, updating the template in the plug-in, deleting all projects on Netlify, Vercel, and Github, and recreating new projects, but it still doesn't work.

I am not a tech person so I don't know how to read the error message and solve the problem. 

On Netlify, it says non-zero exit: 2.

Here is the error message on Vercel:
[19:17:23.231] Running build in San Francisco, USA (West) – sfo1
[19:17:23.291] Cloning github.com/xxx/xxx (Branch: main, Commit: 8ab3aa4)
[19:17:24.199] Cloning completed: 907.196ms
[19:17:24.493] Restored build cache
[19:17:24.522] Running "vercel build"
[19:17:24.969] Vercel CLI 28.18.5
[19:17:25.940] Running "install" command: `npm install`...
[19:17:28.469] 
[19:17:28.470] up to date, audited 555 packages in 2s
[19:17:28.470] 
[19:17:28.470] 98 packages are looking for funding
[19:17:28.470]   run `npm fund` for details
[19:17:28.486] 
[19:17:28.486] 14 vulnerabilities (2 moderate, 9 high, 3 critical)
[19:17:28.486] 
[19:17:28.487] To address issues that do not require attention, run:
[19:17:28.487]   npm audit fix
[19:17:28.487] 
[19:17:28.487] Some issues need review, and may require choosing
[19:17:28.487] a different dependency.
[19:17:28.487] 
[19:17:28.487] Run `npm audit` for details.
[19:17:28.802] 
[19:17:28.802] > web@1.0.0 build
[19:17:28.802] > npm-run-all get-theme build:*
[19:17:28.802] 
[19:17:29.223] 
[19:17:29.223] > web@1.0.0 get-theme
[19:17:29.223] > node src/site/get-theme.js
[19:17:29.223] 
[19:17:29.623] 
[19:17:29.623] > web@1.0.0 build:eleventy
[19:17:29.623] > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
[19:17:29.624] 
[19:17:30.590] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[19:17:30.591] [11ty] 1. Having trouble rendering njk template ./src/site/notes/xxx/xxx.md (via TemplateContentRenderError)
[19:17:30.591] [11ty] 2. Cannot read properties of undefined (reading 'docId') (via TypeError)
[19:17:30.591] [11ty] 
[19:17:30.591] [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'docId')
[19:17:30.591] [11ty]     at Object.render_footnote_anchor_name [as footnote_anchor_name] (/vercel/path0/node_modules/markdown-it-footnote/index.js:12:18)
[19:17:30.592] [11ty]     at Object.render_footnote_ref [as footnote_ref] (/vercel/path0/node_modules/markdown-it-footnote/index.js:30:27)
[19:17:30.592] [11ty]     at Renderer.render (/vercel/path0/node_modules/markdown-it/lib/renderer.js:332:38)
[19:17:30.592] [11ty]     at /vercel/path0/src/helpers/utils.js:17:36
[19:17:30.592] [11ty]     at Array.forEach (<anonymous>)
[19:17:30.592] [11ty]     at namedHeadings (/vercel/path0/src/helpers/utils.js:15:18)
[19:17:30.592] [11ty]     at Core.process (/vercel/path0/node_modules/markdown-it/lib/parser_core.js:54:13)
[19:17:30.592] [11ty]     at MarkdownIt.parse (/vercel/path0/node_modules/markdown-it/lib/index.js:524:13)
[19:17:30.592] [11ty]     at MarkdownIt.render (/vercel/path0/node_modules/markdown-it/lib/index.js:544:36)
[19:17:30.592] [11ty]     at /vercel/path0/node_modules/@11ty/eleventy/src/Engines/Markdown.js:79:38
[19:17:30.593] [11ty] Copied 5 files / Wrote 0 files in 0.18 seconds (v2.0.1)
[19:17:30.611] ERROR: "build:eleventy" exited with 1.
[19:17:30.632] Error: Command "npm run build" exited with 1
[19:17:30.933] Deployment completed
[19:17:30.888] BUILD_UTILS_SPAWN_1: Command "npm run build" exited with 1

Thank you so much!

**Comment by dayne** [comment]
Noticed this open bug report. Can't help with debug what you pasted myself but I can confirm that latest obsdiian + latest obsidian-digital-garden instructions for deploying on vercel work great.

So great I didn't even have any expanded notes needed in the process beyond what I put here:

https://hive.mod0.org/hive/digital-garden/

Perhaps revisit the vercel deployment steps and provide some more details on the error/issues if this is still an open issue for you.

**Comment by BacKinnn** [comment]
Did you have any footnote in the note? I had 2 that points to Excalidraw drawings, and when I delete the footnote and deploy again, everything works
