### ISSUE TITLE
[BUG] Notes containing `{{....}} ` was parsed, preventing npm run build

### ISSUE THREAD

**Issue by eonun** [oleeskild/obsidian-digital-garden#367]
**The note's code fast content containing `{{....}} ` was parsed, preventing npm run build**

# error message

```
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble rendering njk template ./src/site/notes/学习笔记/Linux/Docker常用命令与操作.md (via TemplateContentRenderError)
[11ty] 2. (./src/site/notes/学习笔记/Linux/Docker常用命令与操作.md) [Line 160, Column 28]
[11ty]   unexpected token: . (via Template render error)
[11ty]
[11ty] Original error stack trace: Template render error: (./src/site/notes/学习笔记/Linux/Docker常用命令与操作.md) [Line 160, Column 28]
[11ty]   unexpected token: .
[11ty]     at Object._prettifyError (/home/eonun/eonun.com/node_modules/nunjucks/src/lib.js:32:11)
[11ty]     at Template.init (/home/eonun/eonun.com/node_modules/nunjucks/src/environment.js:416:19)
[11ty]     at Template.Obj (/home/eonun/eonun.com/node_modules/nunjucks/src/object.js:51:15)
[11ty]     at new Template (/home/eonun/eonun.com/node_modules/nunjucks/src/environment.js:390:18)
[11ty]     at Nunjucks.compile (/home/eonun/eonun.com/node_modules/@11ty/eleventy/src/Engines/Nunjucks.js:406:14)
[11ty]     at Markdown.compile (/home/eonun/eonun.com/node_modules/@11ty/eleventy/src/Engines/Markdown.js:68:28)
[11ty]     at TemplateRender.getCompiledTemplate (/home/eonun/eonun.com/node_modules/@11ty/eleventy/src/TemplateRender.js:269:26)
[11ty]     at Template.compile (/home/eonun/eonun.com/node_modules/@11ty/eleventy/src/TemplateContent.js:362:42)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Template._render (/home/eonun/eonun.com/node_modules/@11ty/eleventy/src/TemplateContent.js:486:16)
[11ty] Wrote 0 files in 1.13 seconds (v2.0.1)
ERROR: "build:eleventy" exited with 1.
```

# Location of the error

~~~
cat ./src/site/notes/学习笔记/Linux/Docker常用命令与操作.md
....
```sh
sudo docker inspect -f  '{{.Id}}' [id]
```
....
~~~

The reason for the error should be `{{....}} ` was parsed

**Comment by julesvirallinen** [comment]
Possibly related to https://github.com/oleeskild/obsidian-digital-garden/issues/332

This seems mildly worrying, as it implies some sort of need for escaping / sanitation. Luckily it's just the templating engine, so the security risk probably isn't too dire.

**Comment by oleeskild** [comment]
This has now been fixed in the latest version of the template. [Update the template](https://dg-docs.ole.dev/getting-started/06-updating-the-template/) and text like {{ something }} should no longer be an issue.
