### ISSUE TITLE
Unable to Deploy in Versa

### ISSUE THREAD

**Issue by Kenljs** [oleeskild/obsidian-digital-garden#629]
I installed. published one note to vercel, but now whenever I try to publish a second note or to update that on vercel it gives this error log consistently.

```

[11:44:43.528] Running build in Washington, D.C., USA (East) – iad1
[11:44:43.683] Cloning github.com/Kenljs/gebsierrawiki (Branch: main, Commit: 8392e95)
[11:44:44.295] Cloning completed: 608.955ms
[11:44:45.030] Restored build cache
[11:44:45.117] Running "vercel build"
[11:44:45.575] Vercel CLI 35.2.3
[11:44:48.821] Running "install" command: `npm install`...
[11:44:50.338] 
[11:44:50.339] up to date, audited 498 packages in 1s
[11:44:50.339] 
[11:44:50.339] 131 packages are looking for funding
[11:44:50.339]   run `npm fund` for details
[11:44:50.342] 
[11:44:50.343] 1 high severity vulnerability
[11:44:50.343] 
[11:44:50.343] To address all issues, run:
[11:44:50.343]   npm audit fix
[11:44:50.343] 
[11:44:50.343] Run `npm audit` for details.
[11:44:50.916] 
[11:44:50.917] > web@1.0.0 build
[11:44:50.918] > npm-run-all get-theme build:*
[11:44:50.918] 
[11:44:51.178] 
[11:44:51.180] > web@1.0.0 get-theme
[11:44:51.180] > node src/site/get-theme.js
[11:44:51.180] 
[11:44:51.533] 
[11:44:51.535] > web@1.0.0 build:eleventy
[11:44:51.535] > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
[11:44:51.535] 
[11:44:52.585] [11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11:44:52.587] [11ty] 1. Having trouble rendering md template ./src/site/notes/🗣️🗣️ All TEACHINGS stack/💫 Sermons/💫 Titus Sermons/Titus 3_1-2 - Government Authority Living a Grace-Filled Life.md (via TemplateContentRenderError)
[11:44:52.587] [11ty] 2. Cannot read properties of undefined (reading 'docId') (via TypeError)
[11:44:52.587] [11ty] 
[11:44:52.588] [11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'docId')
[11:44:52.588] [11ty]     at Object.render_footnote_anchor_name [as footnote_anchor_name] (/vercel/path0/node_modules/markdown-it-footnote/index.js:12:18)
[11:44:52.589] [11ty]     at Object.render_footnote_ref [as footnote_ref] (/vercel/path0/node_modules/markdown-it-footnote/index.js:30:27)
[11:44:52.589] [11ty]     at Renderer.render (/vercel/path0/node_modules/markdown-it/dist/index.cjs.js:813:28)
[11:44:52.589] [11ty]     at /vercel/path0/src/helpers/utils.js:17:36
[11:44:52.589] [11ty]     at Array.forEach (<anonymous>)
[11:44:52.589] [11ty]     at namedHeadings (/vercel/path0/src/helpers/utils.js:15:18)
[11:44:52.590] [11ty]     at Core.process (/vercel/path0/node_modules/markdown-it/dist/index.cjs.js:1861:13)
[11:44:52.592] [11ty]     at MarkdownIt.parse (/vercel/path0/node_modules/markdown-it/dist/index.cjs.js:5491:13)
[11:44:52.592] [11ty]     at MarkdownIt.render (/vercel/path0/node_modules/markdown-it/dist/index.cjs.js:5508:36)
[11:44:52.592] [11ty]     at /vercel/path0/node_modules/@11ty/eleventy/src/Engines/Markdown.js:90:24
[11:44:52.593] [11ty] Copied 6 files / Wrote 0 files in 0.32 seconds (v2.0.1)
[11:44:52.612] ERROR: "build:eleventy" exited with 1.
[11:44:52.623] Error: Command "npm run build" exited with 1
[11:44:52.846] 
```

**Comment by kamil-rudnicki** [comment]
Have the same issue. for me footnotes are the problem. If I delete note with footnote it works.
