### ISSUE TITLE
published the first note, after that it does not allow to publish any more

### ISSUE THREAD

**Issue by tuber84** [oleeskild/obsidian-digital-garden#641]
I connected everything according to the instructions, published the first test note to the garden, everything is fine.
![image](https://github.com/user-attachments/assets/1ba1ca60-3d40-4d48-bd39-623fe06c7cbe)

But after that it does not allow publishing a single note, it gives the following errors:
![image](https://github.com/user-attachments/assets/2d94b6ab-2c5b-4c6b-8a9f-c8df56b4d2f3)

`[20:04:56.147] [11ty] 
[20:04:56.147] [11ty] Original error stack trace: (Repeated output has been truncated…)
[20:04:56.147] [11ty]     at TemplateMap.checkForDuplicatePermalinks (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:803:13)
[20:04:56.147] [11ty]     at TemplateMap.cache (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateMap.js:488:10)
[20:04:56.147] [11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[20:04:56.147] [11ty]     at async TemplateWriter._createTemplateMap (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:330:5)
[20:04:56.147] [11ty]     at async TemplateWriter.generateTemplates (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:360:5)
[20:04:56.147] [11ty]     at async TemplateWriter.write (/vercel/path0/node_modules/@11ty/eleventy/src/TemplateWriter.js:407:23)
[20:04:56.147] [11ty]     at async Eleventy.executeBuild (/vercel/path0/node_modules/@11ty/eleventy/src/Eleventy.js:1191:13)
[20:04:56.147] [11ty] Copied 1 file / Wrote 0 files in 0.32 seconds (v2.0.1)
[20:04:56.167] ERROR: "build:eleventy" exited with 1.
[20:04:56.177] Error: Command "npm run build" exited with 1
[20:04:56.339] `

At the same time, in the obsidian itself, it says that everything is OK!:
![image](https://github.com/user-attachments/assets/ebe75a91-a72c-462e-93ed-f24795893bb2)

**Comment by tuber84** [comment]
I found the solution myself, help is a bit confusing, both properties (dg-publish dg-home) are needed only for the home note, for the rest only the dg-publish property is needed.
![image](https://github.com/user-attachments/assets/07c6fd8d-85a8-412f-93bc-f88c70e78ba0)

**Comment by tuber84** [comment]
I found the solution myself, help is a bit confusing, both properties (dg-publish dg-home) are needed only for the home note, for the rest only the dg-publish property is needed.
