### ISSUE TITLE
Deploy fail with Netlify (2.23.0)

### ISSUE THREAD

**Issue by amperag** [oleeskild/obsidian-digital-garden#97]
All of a sudden my builds are failing on netlify (see picture below).

The only thing I did differently with these builds were to update the site settings (Theme, Favicon, ...).
Still what is weird is that the builds were completed successfully a couple of times until they started to fail.

I'm running Digital Garden v. 2.23.0
Repo should be up to date.

I'm attaching the deploy log below.

![image](https://user-images.githubusercontent.com/61867589/201208192-ee0e6ba8-a74b-4b23-94e9-5d717de8f89b.png)

---

```
6:42:03 PM: build-image version: d7b3813f01c06610bc1723ff1b22446513ee7941 (focal)
6:42:03 PM: build-image tag: v4.14.3
6:42:03 PM: buildbot version: b8818322cd07df39ed42700557962e5781043dd7
6:42:03 PM: Fetching cached dependencies
6:42:03 PM: Starting to download cache of 189.9MB
6:42:05 PM: Finished downloading cache in 2.10745276s
6:42:05 PM: Starting to extract cache
6:42:07 PM: Finished extracting cache in 1.494567319s
6:42:07 PM: Finished fetching cache in 3.658252293s
6:42:07 PM: Starting to prepare the repo for build
6:42:07 PM: Preparing Git Reference refs/heads/main
6:42:10 PM: Parsing package.json dependencies
6:42:11 PM: Different functions path detected, going to use the one specified in the Netlify configuration file: 'netlify/functions' versus '' in the Netlify UI
6:42:11 PM: Starting build script
6:42:11 PM: Installing dependencies
6:42:11 PM: Python version set to 2.7
6:42:11 PM: Started restoring cached node version
6:42:12 PM: Finished restoring cached node version
6:42:12 PM: v16.18.1 is already installed.
6:42:13 PM: Now using node v16.18.1 (npm v8.19.2)
6:42:13 PM: Enabling node corepack
6:42:13 PM: Started restoring cached build plugins
6:42:13 PM: Finished restoring cached build plugins
6:42:13 PM: Attempting ruby version 2.7.2, read from environment
6:42:14 PM: Using ruby version 2.7.2
6:42:14 PM: Using PHP version 8.0
6:42:14 PM: No npm workspaces detected
6:42:14 PM: Started restoring cached node modules
6:42:14 PM: Finished restoring cached node modules
6:42:14 PM: Started restoring cached go cache
6:42:14 PM: Finished restoring cached go cache
6:42:14 PM: Installing Go version 1.17 (requested 1.17)
6:42:20 PM: unset GOOS;
6:42:20 PM: unset GOARCH;
6:42:20 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
6:42:20 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
6:42:20 PM: go version >&2;
6:42:20 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
6:42:20 PM: go version go1.17 linux/amd64
6:42:20 PM: Detected 1 framework(s)
6:42:20 PM: "eleventy" at version "1.0.0"
6:42:20 PM: Installing missing commands
6:42:20 PM: Verify run directory
6:42:22 PM: ​
6:42:22 PM: ────────────────────────────────────────────────────────────────
6:42:22 PM:   Netlify Build                                                 
6:42:22 PM: ────────────────────────────────────────────────────────────────
6:42:22 PM: ​
6:42:22 PM: ❯ Version
6:42:22 PM:   @netlify/build 28.1.12
6:42:22 PM: ​
6:42:22 PM: ❯ Flags
6:42:22 PM:   baseRelDir: true
6:42:22 PM:   buildId: 636d37e9f939a00008a3d858
6:42:22 PM:   deployId: 636d37e9f939a00008a3d85a
6:42:22 PM: ​
6:42:22 PM: ❯ Current directory
6:42:22 PM:   /opt/build/repo
6:42:22 PM: ​
6:42:22 PM: ❯ Config file
6:42:22 PM:   /opt/build/repo/netlify.toml
6:42:22 PM: ​
6:42:22 PM: ❯ Context
6:42:22 PM:   production
6:42:22 PM: ​
6:42:22 PM: ────────────────────────────────────────────────────────────────
6:42:22 PM:   1. build.command from netlify.toml                            
6:42:22 PM: ────────────────────────────────────────────────────────────────
6:42:22 PM: ​
6:42:22 PM: $ npm install && npm run build
6:42:24 PM: up to date, audited 605 packages in 2s
6:42:24 PM: 71 packages are looking for funding
6:42:24 PM:   run `npm fund` for details
6:42:24 PM: 8 vulnerabilities (4 moderate, 3 high, 1 critical)
6:42:24 PM: Some issues need review, and may require choosing
6:42:24 PM: a different dependency.
6:42:24 PM: Run `npm audit` for details.
6:42:24 PM: > web@1.0.0 build
6:42:24 PM: > npm-run-all build:*
6:42:24 PM: > web@1.0.0 build:eleventy
6:42:24 PM: > cross-env ELEVENTY_ENV=prod NODE_OPTIONS=--max-old-space-size=4096 eleventy
6:42:25 PM: [11ty] > Request failed with status code 404
6:42:25 PM: `Error` was thrown:
6:42:25 PM: [11ty]     Error: Request failed with status code 404
6:42:25 PM:         at createError (/opt/build/repo/node_modules/axios/lib/core/createError.js:16:15)
6:42:25 PM:         at settle (/opt/build/repo/node_modules/axios/lib/core/settle.js:17:12)
6:42:25 PM:         at IncomingMessage.handleStreamEnd (/opt/build/repo/node_modules/axios/lib/adapters/http.js:322:11)
6:42:25 PM:         at IncomingMessage.emit (node:events:525:35)
6:42:25 PM:         at endReadableNT (node:internal/streams/readable:1358:12)
6:42:25 PM:         at processTicksAndRejections (node:internal/process/task_queues:83:21)
6:42:25 PM: ERROR: "build:eleventy" exited with 1.
6:42:25 PM: ​
6:42:25 PM: ────────────────────────────────────────────────────────────────
6:42:25 PM:   "build.command" failed                                        
6:42:25 PM: ────────────────────────────────────────────────────────────────
6:42:25 PM: ​
6:42:26 PM: Creating deploy upload records
6:42:25 PM:   Error message
6:42:25 PM:   Command failed with exit code 1: npm install && npm run build (https://ntl.fyi/exit-code-1)
6:42:25 PM: ​
6:42:25 PM:   Error location
6:42:26 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
6:42:25 PM:   In build.command from netlify.toml:
6:42:25 PM:   npm install && npm run build
6:42:25 PM: ​
6:42:25 PM:   Resolved config
6:42:25 PM:   build:
6:42:25 PM:     command: npm install && npm run build
6:42:25 PM:     commandOrigin: config
6:42:25 PM:     publish: /opt/build/repo/dist
6:42:25 PM:     publishOrigin: config
6:42:25 PM:   functionsDirectory: /opt/build/repo/netlify/functions
6:42:25 PM:   redirects:
6:42:25 PM:     - from: /api/*      status: 200      to: /.netlify/functions/:splat    - from: /*      status: 404      to: /404  redirectsOrigin: configCaching artifacts
6:42:25 PM: Started saving node modules
6:42:25 PM: Finished saving node modules
6:42:25 PM: Started saving build plugins
6:42:25 PM: Finished saving build plugins
6:42:25 PM: Started saving pip cache
6:42:25 PM: Finished saving pip cache
6:42:25 PM: Started saving emacs cask dependencies
6:42:26 PM: Finished saving emacs cask dependencies
6:42:26 PM: Started saving maven dependencies
6:42:26 PM: Finished saving maven dependencies
6:42:26 PM: Started saving boot dependencies
6:42:26 PM: Finished saving boot dependencies
6:42:26 PM: Started saving rust rustup cache
6:42:26 PM: Finished saving rust rustup cache
6:42:26 PM: Started saving go dependencies
6:42:26 PM: Finished saving go dependencies
6:42:26 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:42:26 PM: Failing build: Failed to build site
6:42:26 PM: Finished processing build request in 22.866916227s
```

**Comment by oleeskild** [comment]
Super weird 🤔 Given that it is a 404 error I think maybe this has to do with the theme. On each build the template sends a request to GitHub for the css of the theme you've chosen. I suspect there is something wrong with that URL. Could you go into your repo and find the file named ".env" and look for a line that starts with "THEME=" followed by a URL and paste that here?

**Comment by oleeskild** [comment]
So the issue indeed was the URL of the theme. The plugin assumed that the branch for the theme was always named master. This was not the case with the Wasp theme, which used "main" instead. I've changed the plugin to instead use whatever the theme has set as their default branch. 
If you update the plugin, and switch to a new theme, before switching back to Wasp again to make sure the plugin uses the new URL, it should work again. Let me know if that fixed it 😄
